sentinel_map:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: SMAIKZB-IZC24119
      user: BRYANLI2011
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: SENTINEL_ROLE
      database: SENTINEL_MAP
      warehouse: SENTINEL_WH
      schema: DBT_DEV
      threads: 4
      client_session_keep_alive: False
