version: 2

sources:
  - name: raw
    database: SENTINEL_MAP
    schema: RAW
    tables:
      - name: stg_detections
        description: "Raw detections streamed from Kafka via Snowpipe"
        columns:
          - name: record_content
            description: "VARIANT column containing detection JSON"
            tests:
              - not_null

      - name: ref_osm_nodes
        description: "OpenStreetMap reference data for Toronto traffic infrastructure"
        columns:
          - name: osm_id
            description: "OSM node identifier"
            tests:
              - not_null
              - unique
          - name: latitude
            description: "Latitude coordinate"
            tests:
              - not_null
          - name: longitude
            description: "Longitude coordinate"
            tests:
              - not_null
